//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        public int IdMascota { get; set; }
        public int Clase { get; set; }
        public int Persona { get; set; }
        public string Nombre { get; set; }
    
        public virtual Clase_Animal Clase_Animal { get; set; }
        public virtual Persona Persona1 { get; set; }
    }
}
